<?php

    use Illuminate\Database\Seeder;

    class StuffsSeeder extends Seeder
    {
        /**
         * Run the database seeds.
         *
         * @return void
         */
        public function run()
        {

            $data = [
                [
                    'id' => '1',
                    'department_id' => '1',
                    'organization_id' => '1',
                    'position_id' => '1',
                    'name' => 'Имя 1',
                    'surname' => 'Фамилия 1',
                    'fathersname' => 'Отчество 1',
                    'email' => 'stuff1@org.tj',
                    'phone' => '7777777',
                    'description' => 'Краткое опсание сотрудника',
                    'status' => '1',
                    'created_user' => '1',
                    'img' => '1.png',
                ],
                [
                    'id' => '2',
                    'department_id' => '1',
                    'organization_id' => '1',
                    'position_id' => '2',
                    'name' => 'Имя 2',
                    'surname' => 'Фамилия 2',
                    'fathersname' => 'Отчество 2',
                    'email' => 'stuff1@org.tj',
                    'phone' => '7777777',
                    'description' => 'Краткое опсание сотрудника',
                    'status' => '1',
                    'created_user' => '1',
                    'img' => '1.png',
                ],
                [
                    'id' => '3',
                    'department_id' => '2',
                    'organization_id' => '1',
                    'position_id' => '1',
                    'name' => 'Имя 3',
                    'surname' => 'Фамилия 3',
                    'fathersname' => 'Отчество 3',
                    'email' => 'stuff1@org.tj',
                    'phone' => '7777777',
                    'description' => 'Краткое опсание сотрудника',
                    'status' => '1',
                    'created_user' => '1',
                    'img' => '1.png',
                ],
                [
                    'id' => '4',
                    'department_id' => '2',
                    'organization_id' => '1',
                    'position_id' => '2',
                    'name' => 'Имя 4',
                    'surname' => 'Фамилия 4',
                    'fathersname' => 'Отчество 4',
                    'email' => 'stuff1@org.tj',
                    'phone' => '7777777',
                    'description' => 'Краткое опсание сотрудника',
                    'status' => '1',
                    'created_user' => '1',
                    'img' => '1.png',
                ],
                [
                    'id' => '5',
                    'department_id' => '3',
                    'organization_id' => '1',
                    'position_id' => '3',
                    'name' => 'Имя 5',
                    'surname' => 'Фамилия 5',
                    'fathersname' => 'Отчество 5',
                    'email' => 'stuff1@org.tj',
                    'phone' => '7777777',
                    'description' => 'Краткое опсание сотрудника',
                    'status' => '1',
                    'created_user' => '1',
                    'img' => '1.png',
                ],
                [
                    'id' => '6',
                    'department_id' => '3',
                    'organization_id' => '1',
                    'position_id' => '1',
                    'name' => 'Имя 6',
                    'surname' => 'Фамилия 6',
                    'fathersname' => 'Отчество 6',
                    'email' => 'stuff1@org.tj',
                    'phone' => '7777777',
                    'description' => 'Краткое опсание сотрудника',
                    'status' => '1',
                    'created_user' => '1',
                    'img' => '1.png',
                ],
                [
                    'id' => '7',
                    'department_id' => '4',
                    'organization_id' => '1',
                    'position_id' => '1',
                    'name' => 'Имя 7',
                    'surname' => 'Фамилия 7',
                    'fathersname' => 'Отчество 7',
                    'email' => 'stuff1@org.tj',
                    'phone' => '7777777',
                    'description' => 'Краткое опсание сотрудника',
                    'status' => '1',
                    'created_user' => '1',
                    'img' => '1.png',
                ],
                [
                    'id' => '8',
                    'department_id' => '4',
                    'organization_id' => '1',
                    'position_id' => '5',
                    'name' => 'Имя 8',
                    'surname' => 'Фамилия 8',
                    'fathersname' => 'Отчество 8',
                    'email' => 'stuff1@org.tj',
                    'phone' => '7777777',
                    'description' => 'Краткое опсание сотрудника',
                    'status' => '1',
                    'created_user' => '1',
                    'img' => '1.png',
                ],
                [
                    'id' => '9',
                    'department_id' => '5',
                    'organization_id' => '1',
                    'position_id' => '1',
                    'name' => 'Имя 9',
                    'surname' => 'Фамилия 9',
                    'fathersname' => 'Отчество 9',
                    'email' => 'stuff1@org.tj',
                    'phone' => '7777777',
                    'description' => 'Краткое опсание сотрудника',
                    'status' => '1',
                    'created_user' => '1',
                    'img' => '1.png',
                ],
                [
                    'id' => '10',
                    'department_id' => '5',
                    'organization_id' => '1',
                    'position_id' => '6',
                    'name' => 'Имя 10',
                    'surname' => 'Фамилия 10',
                    'fathersname' => 'Отчество 10',
                    'email' => 'stuff1@org.tj',
                    'phone' => '7777777',
                    'description' => 'Краткое опсание сотрудника',
                    'status' => '1',
                    'created_user' => '1',
                    'img' => '1.png',
                ],
                [
                    'id' => '11',
                    'department_id' => '6',
                    'organization_id' => '1',
                    'position_id' => '1',
                    'name' => 'Имя 11',
                    'surname' => 'Фамилия 11',
                    'fathersname' => 'Отчество 11',
                    'email' => 'stuff1@org.tj',
                    'phone' => '7777777',
                    'description' => 'Краткое опсание сотрудника',
                    'status' => '1',
                    'created_user' => '1',
                    'img' => '1.png',
                ],
                
            ];

            DB::table('stuffs')->insert($data);
        }
    }
